import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Header from '../components/Header'
import Hero from '../components/Hero'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Image from "next/image";

const Home: NextPage = () => {

  const tokens = [
    { 
      id: 1, 
      name: "Codeva AI", 
      ticker: "CODEVA", 
      marketCap: "$52.2K", 
      replies: 3, 
      chain: "Ethereum", 
      image: "https://picsum.photos/400/300?random=1" // AI/Tech related image
    },
    { 
      id: 2, 
      name: "One Day Challenge", 
      ticker: "1DayChal", 
      marketCap: "$14.0K", 
      replies: 68, 
      chain: "Polygon", 
      image: "https://picsum.photos/400/300?random=2" // Clock-related image
    },
    { 
      id: 3, 
      name: "PIX MIX", 
      ticker: "PIX", 
      marketCap: "$4.7K", 
      replies: 22, 
      chain: "Solana", 
      image: "https://picsum.photos/400/300?random=3" // Pixel-art / gaming image
    },
    { 
      id: 4, 
      name: "The Final Sendor", 
      ticker: "SENDOR", 
      marketCap: "$12.5K", 
      replies: 35, 
      chain: "Base", 
      image: "https://picsum.photos/400/300?random=4" // Futuristic space image
    },
  ];
  

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <Hero />
      <main className="container mx-auto p-6">
        <h2 className="text-2xl font-bold mb-4">Live & Upcoming Token Launches</h2>

       {/* Grid Layout */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {tokens.map((token) => (
            <Link key={token.id} href={`/token/${token.id}`} passHref>
              <div className="cursor-pointer bg-[#111827] bg-opacity-80 backdrop-blur-lg border border-[#292B3A] hover:border-[#7B3FE4] 
                p-5 rounded-xl shadow-xl transform transition duration-300 hover:scale-105 hover:shadow-neon-glow relative group h-full flex flex-col">
                
                {/* Image Wrapper (Fixed Aspect Ratio) */}
                <div className="relative w-full h-40 overflow-hidden rounded-lg">
                  <Image 
                    src={token.image} 
                    alt={token.name} 
                    layout="fill"
                    objectFit="cover"
                    className="transition-all duration-300 group-hover:scale-110 rounded-lg"
                  />
                </div>

                {/* Token Details (Flexbox to push elements evenly) */}
                <div className="flex flex-col flex-grow mt-4">
                  <h3 className="text-2xl font-semibold text-white tracking-wide group-hover:text-[#7B3FE4] transition duration-300">
                    {token.name} ({token.ticker})
                  </h3>
                  <p className="text-sm text-gray-400 mt-1">Market Cap: <span className="text-green-400">{token.marketCap}</span></p>
                  <p className="text-sm text-gray-400">Replies: {token.replies}</p>
                  <p className="text-xs text-blue-400">{token.chain}</p>
                </div>
              </div>
            </Link>
          ))}
        </div>

        <div className="mt-6">
          <Link href="/create">
            <button className="px-4 py-2 bg-blue-600 text-white rounded-lg">
              + Create New Token
            </button>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
